CC = g++
CFLAGS = -Wall 

# Compile commands 
pi: 
	$(CC) $(CFLAGS) compute_pi.cpp -o pi 

all: 
	$(CC) $(CFLAGS) compute_pi.cpp -o pi

# Run commands 
run_pi: 
	./pi
run_all: 
	./pi
# Clean commands 
clean: 
	rm -rf *.o *.dat *.txt pi